global:
  scrape_interval: 10s # Server 抓取頻率

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - '10.0.101.31:9100'
        - '10.0.101.33:9100'

  - job_name: 'blackbox'
    scrape_interval: 10s 
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://www.google.com
        - https://www.github.com
        - https://www.wikipedia.org
        - https://www.stackoverflow.com
        - https://www.amazon.com
        - https://www.facebook.com
        - https://www.linkedin.com
        - https://www.netflix.com
        - https://www.apple.com
        - https://www.spotify.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # The blackbox exporter's real hostname:port.

  - job_name: 'blackbox_exporter'  # collect blackbox exporter's operational metrics.
    static_configs:
      - targets: ['blackbox-exporter:9115']

  - job_name: 'uptime_kuma'
    scrape_interval: 10s
    scheme: http
    metrics_path: '/metrics'
    static_configs:
      - targets: ['uptime-kuma:3001']
    basic_auth: # Only needed if authentication is enabled (default) 
      password: 'uk3_0KOAvpzLLRl-1aSrC8CgUYGrlHXPGLuNr7kuPZyU'

  - job_name: "cadvisor"
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          group: 'cadvisor'
